<?php
require 'Characters.php';

class Mage extends Characters{

    public function __construct($name, $rpgClass)
    {
        parent::__construct($name, $rpgClass);
        $this->name = $name;
        $this->rpgClass = $rpgClass;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getLife()
    {
        return $this->life;
    }

    /**
     * @param mixed $life
     */
    public function setLife($life)
    {
        $this->life = $life;
    }

    /**
     * @return mixed
     */
    public function getAgility()
    {
        return $this->agility;
    }

    /**
     * @param mixed $agility
     */
    public function setAgility($agility)
    {
        $this->agility = $agility;
    }

    /**
     * @return mixed
     */
    public function getStrenght()
    {
        return $this->strenght;
    }

    /**
     * @param mixed $strenght
     */
    public function setStrenght($strenght)
    {
        $this->strenght = $strenght;
    }

    /**
     * @return mixed
     */
    public function getWit()
    {
        return $this->wit;
    }

    /**
     * @param mixed $wit
     */
    public function setWit($wit)
    {
        $this->wit = $wit;
    }

    public function main()
    {
        $wizard = new Mage('toto', 'Warriors');
        echo $wizard->getName().PHP_EOL;
        echo $wizard->setLife(100);
        echo $wizard->getLife().PHP_EOL;
        echo $wizard->setAgility(8);
        echo $wizard->getAgility().PHP_EOL;
        echo $wizard->setStrenght(10);
        echo $wizard->getStrenght().PHP_EOL;
        echo $wizard->getRpgClass().PHP_EOL;
        echo $wizard->setWit(3);
        echo $wizard->getWit().PHP_EOL;
        echo $wizard->attack();
    }

    public function attack()
    {
        parent::attack(); // TODO: Change the autogenerated stub
        return "I'll crush you with my ";
    }

}

$wizard = new Mage("toto", 'haha');

var_dump($wizard->main());